### PR TITLE
[WIP] instances/x64: Switch VM type to improve availability

### PR DESCRIPTION
**Pull request by phlax**

### CODE REVIEW

**Comment by phlax** [comment]
cc @mum4k this has been applied

cc @Mythra

**Review by mum4k — APPROVED** [review]

**Comment by phlax** [comment]
apologies i should have WIPped this when the update failed

it was reverted and working with @Mythra to try and figure out a better strategy for this

**Comment by mum4k** [comment]
Please feel free to assign me again if this needs a review.

**Comment by phlax** [comment]
probs we can close this as it was superseeded by other updates

which reminds me i had to make a distressed update today - ill pr shortly the change ...

**Pull request closed without merging**
