### PR TITLE
ami/os: Update to Ubuntu Jammy (22.04)

### LINKED ISSUE #18: Update AMI OS image to `jammy`

### PR DESCRIPTION
**Pull request by phlax**
This should include a kernel which supports `io_uring`

Fix #18

### CODE REVIEW

**Comment by phlax** [comment]
@mum4k there is a high chance that this does not work

in particular due to openssl version conflicts with `.net` (seems to be using a version from the 90s)

https://github.com/microsoft/azure-pipelines-agent/issues/3834

i have added a workaround that i saw variously discussed and seems to be necessary

**Comment by phlax** [comment]
and updated the agent version to pre-release as that also seems likely to be necessary

**Comment by phlax** [comment]
cc @KBaichoo

**Comment by mum4k** [comment]
Ack @phlax. Let me know when this is ready for a test.

**Comment by mum4k** [comment]
We have agreed offline to shelve this until the incompatibility issues between Ubuntu Jammy and the AZP agent are resolved.

**Comment by KBaichoo** [comment]
can you expand more on the incompatability issue / what expected timeline would look like @mum4k ?

**Comment by mum4k** [comment]
On Jammy we are hitting the following issue:

```
==> amazon-ebs: E: Unable to locate package liblttng-ust0
```

Which seems to be this problem: https://github.com/microsoft/azure-pipelines-agent/issues/3834#issuecomment-1119388567

I don't think there is an announced timeline from AZP currently (@phlax please comment if you know more). We have discussed a couple of possible ways to hack it, but neither is clean enough to do unless we really have to as it could compromise the quality of the agent VMs.

**Comment by phlax** [comment]
not sure about timelines - there are a few issues but essentially afaict you have to use a pre-release version of the agent, and even then hack the script

there are reports of people doing this successfully, and im happy to experiment further and/or confirm above, but would rather wait until the next `main` release is out of the way

**Comment by KBaichoo** [comment]
Seems like the incompatibility issue might have been solved based on https://github.com/microsoft/azure-pipelines-agent/issues/3834#issuecomment-1539426271

**Comment by phlax** [comment]
yeah it mostly has (last time i checked) and we have a hack here for the remaining bits 

https://github.com/envoyproxy/ci-infra/blob/1a093b5933ca37e0f80ec75ef60ec41184078850/ami-build/scripts/install-fun.sh#L150-L162

we need to hook up the existing pools to the new scripts - its on our radar, cc @mum4k

**Comment by phlax** [comment]
this is now updated, so closing

**Pull request closed without merging**
